version: '3'
services:
  web:
    build:
      context: . # the host path to the project
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules # just bookmark, don't bind
      - .:/app
